version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@2026
      POSTGRES_DB: synapse
    ports:
      - '5432:5432'