author: Kamaleshwaran
description: This GitHub Actions workflow automates the deployment of a React application to GitHub Pages whenever changes are pushed to the main branch. It checks out the code, sets up Node.js, installs dependencies, builds the project, and then deploys the built files to the gh-pages branch using the peaceiris/actions-gh-pages action.*/


name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build the Project
        run: npm run build

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist